version: '3.8'
services:
  nextcloud-mariadb:
    image: safespring/nextcloud-mariadb:10.5.5-1
    environment:
      MYSQL_ROOT_PASSWORD: M5H&%@-0BgY3312Nws2g
      BOOTSTRAP: 0
      FORCE_BOOTSTRAP: 0
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ${PWD}/datadir:/var/lib/mysql
      - ${PWD}/init:/docker-entrypoint-initdb.d
      - ${PWD}/conf:/etc/mysql/mariadb.conf.d
      - ${PWD}/backups:/backups
    ulimits:
      nofile:
        soft: 256000
        hard: 256000
    command:
      - --wsrep_cluster_address=gcomm://89.45.237.193,89.45.237.218,89.45.237.133

  mariadb-exporter:
    image: prom/mysqld-exporter:latest
    depends_on:
      - nextcloud-mariadb
    environment:
      DATA_SOURCE_NAME: "exporter:BjF4242g5bYRswX490Mw@(127.0.0.1:3306)/information_schema"
    network_mode: "host"
    restart: on-failure
