version: '3.8'
services:
  nextcloud-proxysql:
    image: safespring/nextcloud-proxysql:2.0.14-1
    environment:
      INITIALIZE: 0
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ${PWD}/proxysql.cnf:/etc/proxysql.cnf
      - ${PWD}/conf:/etc/mysql/conf.d/
